services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/front.conf:/etc/nginx/conf.d/front.conf:ro
      - ./nginx/api.conf:/etc/nginx/conf.d/api.conf:ro
      - front_build:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - app-network

  backend:
    image: ghcr.io/alexandre-richard/reunion-backend:latest
    container_name: backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_PORT: ${DB_PORT}
      CORS_ORIGIN: ${CORS_ORIGIN}
    expose:
      - "${LOCAL_PORT}"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: ghcr.io/alexandre-richard/reunion-frontend:latest
    container_name: frontend-builder
    environment:
      VITE_API_ADRESS: ${VITE_API_ADRESS}
    command: ["sh", "-c", "cp -r /app/build/* /usr/share/nginx/html"]
    volumes:
      - front_build:/usr/share/nginx/html
    restart: "no"
    networks:
      - app-network

  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - ./mariadb-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app-network

volumes:
  front_build:

networks:
  app-network:
    driver: bridge
