services:
  db-init:
    image: alpine:3.19
    env_file:
      - .env
    volumes:
      - ./db-init:/templates:ro
      - ./db-init-generated:/generated
    command: >
      sh -c "apk add --no-cache gettext &&
             envsubst < /templates/00_init_database.sql.template > /generated/00-init.sql"
    restart: "no"

  migrations:
    image: ghcr.io/alexandre-richard/reunification-backend:v0.0.1_alpha4
    command: >
      sh -c "
      if [ -d /app/migrations ] && [ \"$(ls -A /app/migrations)\" ]; then
        cp -r /app/migrations/* /shared-migrations;
      else
        echo 'No migrations found';
      fi
      "
    volumes:
      - backend-migrations:/shared-migrations
    networks:
      - app-network
    restart: "no"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/front.conf:/etc/nginx/conf.d/front.conf:ro
      - ./nginx/api.conf:/etc/nginx/conf.d/api.conf:ro
      - front_build:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - app-network

  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./db-init-generated:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app-network
    ports:
      - "127.0.0.1:3306:${DB_PORT}"

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      mariadb:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - backend-migrations:/flyway/sql
    command: >
      migrate
      -connectRetries=10
      -url=jdbc:${DB_HOST}://${DB_HOST}:${DB_PORT}/${DB_DATABASE_NAME}
      -user=${DB_USER_NAME}
      -password=${DB_USER_PASSWORD}
    networks:
      - app-network
    restart: "no"

  backend:
    image: ghcr.io/alexandre-richard/reunification-backend:v0.0.1_alpha4
    container_name: backend
    depends_on:
      flyway:
        condition: service_completed_successfully
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_PORT: ${DB_PORT}
      CORS_ORIGIN: ${CORS_ORIGIN}
      LOCAL_PORT: ${API_PORT}
    expose:
      - "${API_PORT}"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: ghcr.io/alexandre-richard/reunification-frontend:v0.0.1_alpha2
    container_name: frontend-builder
    environment:
      VITE_API_ADRESS: ${VITE_API_ADRESS}
    command: ["sh", "-c", "cp -r /app/build/* /usr/share/nginx/html"]
    volumes:
      - front_build:/usr/share/nginx/html
    restart: "no"
    networks:
      - app-network

volumes:
  front_build:
  backend-migrations:

networks:
  app-network:
    driver: bridge
